# Change these first
owner: nuke86 # Your GitHub organization or username, where this repository lives
repo: ransomPing # The name of this repository

sites:
  - name: Affari Esteri e Cooperazione Internazionale
    url: http://www.esteri.it/
  - name: Interno
    url: https://www.interno.gov.it/
  - name: Giustizia
    url: http://www.giustizia.it/
  - name: Difesa
    url: http://www.difesa.it/
  - name: Economia e Finanze
    url: http://www.mef.gov.it/
  - name: Imprese e Made in Italy
    url: https://www.mise.gov.it/
  - name: Agricoltura, Sovranità alimentare e Foreste
    url: http://www.politicheagricole.it/
  - name: Ambiente e Sicurezza energetica
    url: https://www.mite.gov.it/    
  - name: Infrastrutture e Trasporti
    url: http://www.mit.gov.it/
  - name: Lavoro e Politiche Sociali
    url: http://www.lavoro.gov.it/
  - name: Istruzione e Merito
    url: https://www.miur.gov.it/
  - name: Università e ricerca
    url: https://www.mur.gov.it/it
  - name: Cultura
    url: http://www.beniculturali.it/
  - name: Salute
    url: http://www.salute.gov.it/
  - name: Turismo
    url: https://www.ministeroturismo.gov.it/
  - name: Carabinieri
    url: http://www.carabinieri.it/
  - name: Polizia di Stato
    url: https://www.poliziadistato.it/
  - name: Guardia di Finanza
    url: https://www.gdf.it
  - name: Governo
    url: https://www.governo.it/
  - name: Presidenza della Repubblica
    url: http://www.quirinale.it/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /ransomPing
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
